USE [sondacoredb]
GO
/****** Object:  Table [dbo].[SIR_AGENTE]    Script Date: 19/10/2022 10:50:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SIR_AGENTE](
	[ID_AGENTE] [int] NOT NULL,
	[ID_ESTADO] [int] NOT NULL,
	[COD_AGENTE] [varchar](20) NOT NULL,
	[DESCRIPCION_AGENTE] [varchar](60) NOT NULL,
	[URL_AGENTE] [varchar](255) NOT NULL,
	[IP_AGENTE] [varchar](50) NOT NULL,
	[FREC_ACTUALIZACION] [int] NOT NULL,
	[MAX_DATA_TRANSFER] [int] NOT NULL,
	[ESTADO_REG] [varchar](1) NULL,
	[FEC_ESTADO_REG] [datetime] NULL,
	[FEC_ING_REG] [datetime] NULL,
	[ID_USUARIO_ING_REG] [varchar](20) NULL,
	[FEC_ULT_MODIF_REG] [datetime] NULL,
	[ID_USUARIO_ULT_MODIF_REG] [varchar](20) NULL,
	[ID_FUNCION_ULT_MODIF_REG] [varchar](16) NULL,
 CONSTRAINT [PK_SIR_AGENTE] PRIMARY KEY NONCLUSTERED 
(
	[ID_AGENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SIR_ESTADO_IMPRESORAS]    Script Date: 19/10/2022 10:50:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SIR_ESTADO_IMPRESORAS](
	[ID_ESTADO] [int] NOT NULL,
	[DESCRIPCION_ESTADO] [varchar](20) NOT NULL,
	[ESTADO_REG] [varchar](1) NULL,
	[FEC_ESTADO_REG] [datetime] NULL,
	[FEC_ING_REG] [datetime] NULL,
	[ID_USUARIO_ING_REG] [varchar](20) NULL,
	[FEC_ULT_MODIF_REG] [datetime] NULL,
	[ID_USUARIO_ULT_MODIF_REG] [varchar](20) NULL,
	[ID_FUNCION_ULT_MODIF_REG] [varchar](16) NULL,
 CONSTRAINT [PK_SIR_ESTADO_IMPRESORAS] PRIMARY KEY NONCLUSTERED 
(
	[ID_ESTADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SIR_ESTADOS_IMPRESION]    Script Date: 19/10/2022 10:50:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SIR_ESTADOS_IMPRESION](
	[ID_ESTADO_IMPRESION] [int] NOT NULL,
	[DESCRIPCION_EST_IMP] [varchar](20) NOT NULL,
	[ESTADO_REG] [varchar](1) NULL,
	[FEC_ESTADO_REG] [datetime] NULL,
	[FEC_ING_REG] [datetime] NULL,
	[ID_USUARIO_ING_REG] [varchar](20) NULL,
	[FEC_ULT_MODIF_REG] [datetime] NULL,
	[ID_USUARIO_ULT_MODIF_REG] [varchar](20) NULL,
	[ID_FUNCION_ULT_MODIF_REG] [varchar](16) NULL,
 CONSTRAINT [PK_SIR_ESTADOS_IMPRESION] PRIMARY KEY NONCLUSTERED 
(
	[ID_ESTADO_IMPRESION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SIR_IMPRESORA]    Script Date: 19/10/2022 10:50:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SIR_IMPRESORA](
	[ID_IMPRESORA] [int] NOT NULL,
	[ID_AGENTE] [int] NOT NULL,
	[ID_PROPOSITO] [int] NULL,
	[NOMBRE_IMPRESORA] [varchar](100) NOT NULL,
	[DESCRIPCION_IMPRESORA] [varchar](60) NULL,
	[IP_UBICACION] [varchar](30) NULL,
	[ID_TP_IMPRESORA] [int] NULL,
	[ID_ESTADO] [int] NULL,
	[ID_TIPO_DOC] [int] NULL,
	[PARAMETROS] [varchar](max) NULL,
	[PROPIEDADES] [varchar](max) NULL,
	[ESTADO_REG] [varchar](1) NULL,
	[FEC_ESTADO_REG] [datetime] NULL,
	[FEC_ING_REG] [datetime] NULL,
	[ID_USUARIO_ING_REG] [varchar](20) NULL,
	[FEC_ULT_MODIF_REG] [datetime] NULL,
	[ID_USUARIO_ULT_MODIF_REG] [varchar](20) NULL,
	[ID_FUNCION_ULT_MODIF_REG] [varchar](16) NULL,
 CONSTRAINT [PK_SIR_IMPRESORA] PRIMARY KEY NONCLUSTERED 
(
	[ID_IMPRESORA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SIR_PROPOSITO]    Script Date: 19/10/2022 10:50:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SIR_PROPOSITO](
	[ID_PROPOSITO] [int] NOT NULL,
	[DESCRIPCION_PROPOSITO] [varchar](60) NOT NULL,
	[ESTADO_REG] [varchar](1) NULL,
	[FEC_ESTADO_REG] [datetime] NULL,
	[FEC_ING_REG] [datetime] NULL,
	[ID_USUARIO_ING_REG] [varchar](20) NULL,
	[FEC_ULT_MODIF_REG] [datetime] NULL,
	[ID_USUARIO_ULT_MODIF_REG] [varchar](20) NULL,
	[ID_FUNCION_ULT_MODIF_REG] [varchar](16) NULL,
 CONSTRAINT [PK_SIR_PROPOSITO] PRIMARY KEY NONCLUSTERED 
(
	[ID_PROPOSITO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SIR_TIPO_DOCUMENTO]    Script Date: 19/10/2022 10:50:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SIR_TIPO_DOCUMENTO](
	[ID_TIPO_DOC] [int] NOT NULL,
	[DESC_TIPO_DOC] [varchar](60) NOT NULL,
	[ESTADO_REG] [varchar](1) NULL,
	[FEC_ESTADO_REG] [datetime] NULL,
	[FEC_ING_REG] [datetime] NULL,
	[ID_USUARIO_ING_REG] [varchar](20) NULL,
	[FEC_ULT_MODIF_REG] [datetime] NULL,
	[ID_USUARIO_ULT_MODIF_REG] [varchar](20) NULL,
	[ID_FUNCION_ULT_MODIF_REG] [varchar](16) NULL,
 CONSTRAINT [PK_SIR_TIPO_DOCUMENTO] PRIMARY KEY NONCLUSTERED 
(
	[ID_TIPO_DOC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SIR_TIPO_IMPRESORA]    Script Date: 19/10/2022 10:50:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SIR_TIPO_IMPRESORA](
	[ID_TP_IMPRESORA] [int] NOT NULL,
	[DESC_TP_IMPRESORA] [varchar](60) NOT NULL,
	[ESTADO_REG] [varchar](1) NULL,
	[FEC_ESTADO_REG] [datetime] NULL,
	[FEC_ING_REG] [datetime] NULL,
	[ID_USUARIO_ING_REG] [varchar](20) NULL,
	[FEC_ULT_MODIF_REG] [datetime] NULL,
	[ID_USUARIO_ULT_MODIF_REG] [varchar](20) NULL,
	[ID_FUNCION_ULT_MODIF_REG] [varchar](16) NULL,
 CONSTRAINT [PK_SIR_TIPO_IMPRESORA] PRIMARY KEY NONCLUSTERED 
(
	[ID_TP_IMPRESORA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SIR_TRABAJOS_IMPRESION]    Script Date: 19/10/2022 10:50:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SIR_TRABAJOS_IMPRESION](
	[ID_TRABAJO] [int] NOT NULL,
	[ID_IMPRESORA] [int] NOT NULL,
	[ID_ESTADO_IMPRESION] [int] NOT NULL,
	[ID_USUARIO] [varchar](20) NULL,
	[POS_COLA_IMPRESION] [int] NULL,
	[DOCUMENTO] [varbinary](max) NULL,
	[NOMBRE_ARCHIVO] [varchar](300) NULL,
	[CONFIG_IMPRESION] [varchar](max) NULL,
	[FECHA_IMPRESION] [datetime] NULL,
	[ESTADO_REG] [varchar](1) NULL,
	[FEC_ESTADO_REG] [datetime] NULL,
	[FEC_ING_REG] [datetime] NULL,
	[ID_USUARIO_ING_REG] [varchar](20) NULL,
	[FEC_ULT_MODIF_REG] [datetime] NULL,
	[ID_USUARIO_ULT_MODIF_REG] [varchar](20) NULL,
	[ID_FUNCION_ULT_MODIF_REG] [varchar](16) NULL,
 CONSTRAINT [PK_SIR_TRABAJOS_IMPRESION] PRIMARY KEY NONCLUSTERED 
(
	[ID_TRABAJO] ASC,
	[ID_IMPRESORA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SIR_USUARIO_IMPRESORAS]    Script Date: 19/10/2022 10:50:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SIR_USUARIO_IMPRESORAS](
	[ID_ADM] [smallint] NOT NULL,
	[ID_IMPRESORA] [int] NOT NULL,
	[ID_USUARIO] [varchar](20) NOT NULL,
	[IMPRESORA_DEFAULT] [bit] NULL,
	[ESTADO_REG] [varchar](1) NULL,
	[FEC_ESTADO_REG] [datetime] NULL,
	[FEC_ING_REG] [datetime] NULL,
	[ID_USUARIO_ING_REG] [varchar](20) NULL,
	[FEC_ULT_MODIF_REG] [datetime] NULL,
	[ID_USUARIO_ULT_MODIF_REG] [varchar](20) NULL,
	[ID_FUNCION_ULT_MODIF_REG] [varchar](16) NULL,
 CONSTRAINT [PK_SIR_USUARIO_IMPRESORAS] PRIMARY KEY NONCLUSTERED 
(
	[ID_ADM] ASC,
	[ID_IMPRESORA] ASC,
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[sys_BaseMensaje]    Script Date: 19/10/2022 10:50:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[sys_BaseMensaje](
	[Codigo] [varchar](50) NULL,
	[Severidad] [int] NULL,
	[Tipo] [varchar](100) NULL,
	[Texto] [varchar](250) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[sys_MensajesLog]    Script Date: 19/10/2022 10:50:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[sys_MensajesLog](
	[Id] [varchar](64) NULL,
	[Fecha] [datetime] NULL,
	[Codigo] [varchar](50) NULL,
	[Severidad] [int] NULL,
	[Tipo] [varchar](100) NULL,
	[Objeto] [varchar](250) NULL,
	[Parametros_Objeto] [varchar](max) NULL,
	[Parametros_Mensaje] [varchar](max) NULL,
	[Texto_Original] [varchar](250) NULL,
	[Texto_Editado] [varchar](250) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USU_USUARIOS]    Script Date: 19/10/2022 10:50:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USU_USUARIOS](
	[ID_ADM] [smallint] NOT NULL,
	[ID_USUARIO] [varchar](20) NOT NULL,
	[ID_PERSONA] [varchar](15) NOT NULL,
	[NOMBRE] [varchar](30) NULL,
	[ESTADO] [varchar](10) NOT NULL,
	[TELEFONO] [varchar](15) NULL,
	[DIRECCION] [varchar](45) NULL,
	[COD_CARGO] [smallint] NULL,
	[COD_AGENCIA] [smallint] NULL,
	[COD_COMUNA] [int] NULL,
	[COD_AREA] [smallint] NULL,
	[IND_BLOQUEO] [varchar](1) NOT NULL,
	[ID_USUARIO_JEFE] [varchar](20) NULL,
	[CLAVE] [varchar](50) NOT NULL,
	[FEC_EXP_CLAVE] [datetime] NOT NULL,
	[CANT_INTENTOS] [smallint] NULL,
	[FEC_ULT_INGRESO] [datetime] NULL,
	[COD_SAFP] [varchar](16) NULL,
	[EMAIL] [varchar](200) NULL,
	[ID_ACTIVE_DIRECTORY] [varchar](200) NULL,
	[HASH_INTEGRIDAD] [varchar](200) NULL,
	[ESTADO_REG] [varchar](1) NULL,
	[FEC_ESTADO_REG] [datetime] NULL,
	[FEC_ING_REG] [datetime] NULL,
	[ID_USUARIO_ING_REG] [varchar](20) NULL,
	[FEC_ULT_MODIF_REG] [datetime] NULL,
	[ID_USUARIO_ULT_MODIF_REG] [varchar](20) NULL,
	[ID_FUNCION_ULT_MODIF_REG] [varchar](16) NULL,
 CONSTRAINT [PK_USU_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[ID_ADM] ASC,
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SIR_AGENTE]  WITH CHECK ADD  CONSTRAINT [FK_EST_IMPRESORA_AGENTE] FOREIGN KEY([ID_ESTADO])
REFERENCES [dbo].[SIR_ESTADO_IMPRESORAS] ([ID_ESTADO])
GO
ALTER TABLE [dbo].[SIR_AGENTE] CHECK CONSTRAINT [FK_EST_IMPRESORA_AGENTE]
GO
ALTER TABLE [dbo].[SIR_IMPRESORA]  WITH CHECK ADD  CONSTRAINT [FK_SIR_IMPR_ESTADO_DE_SIR_ESTA] FOREIGN KEY([ID_ESTADO])
REFERENCES [dbo].[SIR_ESTADO_IMPRESORAS] ([ID_ESTADO])
GO
ALTER TABLE [dbo].[SIR_IMPRESORA] CHECK CONSTRAINT [FK_SIR_IMPR_ESTADO_DE_SIR_ESTA]
GO
ALTER TABLE [dbo].[SIR_IMPRESORA]  WITH CHECK ADD  CONSTRAINT [FK_SIR_IMPR_IMPRESORA_SIR_AGEN] FOREIGN KEY([ID_AGENTE])
REFERENCES [dbo].[SIR_AGENTE] ([ID_AGENTE])
GO
ALTER TABLE [dbo].[SIR_IMPRESORA] CHECK CONSTRAINT [FK_SIR_IMPR_IMPRESORA_SIR_AGEN]
GO
ALTER TABLE [dbo].[SIR_IMPRESORA]  WITH CHECK ADD  CONSTRAINT [FK_SIR_IMPR_IMPRESORA_SIR_TIPO] FOREIGN KEY([ID_TP_IMPRESORA])
REFERENCES [dbo].[SIR_TIPO_IMPRESORA] ([ID_TP_IMPRESORA])
GO
ALTER TABLE [dbo].[SIR_IMPRESORA] CHECK CONSTRAINT [FK_SIR_IMPR_IMPRESORA_SIR_TIPO]
GO
ALTER TABLE [dbo].[SIR_IMPRESORA]  WITH CHECK ADD  CONSTRAINT [FK_SIR_IMPR_PROPOSITO_SIR_PROP] FOREIGN KEY([ID_PROPOSITO])
REFERENCES [dbo].[SIR_PROPOSITO] ([ID_PROPOSITO])
GO
ALTER TABLE [dbo].[SIR_IMPRESORA] CHECK CONSTRAINT [FK_SIR_IMPR_PROPOSITO_SIR_PROP]
GO
ALTER TABLE [dbo].[SIR_IMPRESORA]  WITH CHECK ADD  CONSTRAINT [FK_SIR_IMPR_REF_SIR_TIPO_DOC] FOREIGN KEY([ID_TIPO_DOC])
REFERENCES [dbo].[SIR_TIPO_DOCUMENTO] ([ID_TIPO_DOC])
GO
ALTER TABLE [dbo].[SIR_IMPRESORA] CHECK CONSTRAINT [FK_SIR_IMPR_REF_SIR_TIPO_DOC]
GO
ALTER TABLE [dbo].[SIR_TRABAJOS_IMPRESION]  WITH CHECK ADD  CONSTRAINT [FK_SIR_TRAB_ENVIADOS__SIR_IMPR] FOREIGN KEY([ID_IMPRESORA])
REFERENCES [dbo].[SIR_IMPRESORA] ([ID_IMPRESORA])
GO
ALTER TABLE [dbo].[SIR_TRABAJOS_IMPRESION] CHECK CONSTRAINT [FK_SIR_TRAB_ENVIADOS__SIR_IMPR]
GO
ALTER TABLE [dbo].[SIR_TRABAJOS_IMPRESION]  WITH CHECK ADD  CONSTRAINT [FK_SIR_TRAB_EST_TRABA_SIR_ESTA] FOREIGN KEY([ID_ESTADO_IMPRESION])
REFERENCES [dbo].[SIR_ESTADOS_IMPRESION] ([ID_ESTADO_IMPRESION])
GO
ALTER TABLE [dbo].[SIR_TRABAJOS_IMPRESION] CHECK CONSTRAINT [FK_SIR_TRAB_EST_TRABA_SIR_ESTA]
GO
ALTER TABLE [dbo].[SIR_USUARIO_IMPRESORAS]  WITH CHECK ADD  CONSTRAINT [FK_SIR_USUA_IMPRESORA_SIR_IMPR] FOREIGN KEY([ID_IMPRESORA])
REFERENCES [dbo].[SIR_IMPRESORA] ([ID_IMPRESORA])
GO
ALTER TABLE [dbo].[SIR_USUARIO_IMPRESORAS] CHECK CONSTRAINT [FK_SIR_USUA_IMPRESORA_SIR_IMPR]
GO
ALTER TABLE [dbo].[SIR_USUARIO_IMPRESORAS]  WITH CHECK ADD  CONSTRAINT [FK_SIR_USUA_REGISTRA_SIR_USUA] FOREIGN KEY([ID_ADM], [ID_USUARIO])
REFERENCES [dbo].[USU_USUARIOS] ([ID_ADM], [ID_USUARIO])
GO
ALTER TABLE [dbo].[SIR_USUARIO_IMPRESORAS] CHECK CONSTRAINT [FK_SIR_USUA_REGISTRA_SIR_USUA]
GO
ALTER TABLE [dbo].[USU_USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_USU_USUARIOS_PAR_AGENCIAS] FOREIGN KEY([ID_ADM], [COD_AGENCIA])
REFERENCES [dbo].[PAR_AGENCIAS] ([ID_ADM], [COD_AGENCIA])
GO
ALTER TABLE [dbo].[USU_USUARIOS] CHECK CONSTRAINT [FK_USU_USUARIOS_PAR_AGENCIAS]
GO
ALTER TABLE [dbo].[USU_USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_USU_USUARIOS_PAR_AREAS] FOREIGN KEY([ID_ADM], [COD_AREA])
REFERENCES [dbo].[PAR_AREAS] ([ID_ADM], [COD_AREA])
GO
ALTER TABLE [dbo].[USU_USUARIOS] CHECK CONSTRAINT [FK_USU_USUARIOS_PAR_AREAS]
GO
ALTER TABLE [dbo].[USU_USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_USU_USUARIOS_PAR_COMUNAS] FOREIGN KEY([COD_COMUNA])
REFERENCES [dbo].[PAR_COMUNAS] ([COD_COMUNA])
GO
ALTER TABLE [dbo].[USU_USUARIOS] CHECK CONSTRAINT [FK_USU_USUARIOS_PAR_COMUNAS]
GO
ALTER TABLE [dbo].[USU_USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_USU_USUARIOS_PAR_TIPOS_CARGOS] FOREIGN KEY([ID_ADM], [COD_CARGO])
REFERENCES [dbo].[PAR_TIPOS_CARGOS] ([ID_ADM], [COD_CARGO])
GO
ALTER TABLE [dbo].[USU_USUARIOS] CHECK CONSTRAINT [FK_USU_USUARIOS_PAR_TIPOS_CARGOS]
GO
