IF EXISTS(SELECT 1 FROM sys.views WHERE name='VW_RPT_IMPRESORAS_USUARIOS')
BEGIN
	DROP VIEW dbo.VW_RPT_IMPRESORAS_USUARIOS
END
GO

CREATE VIEW dbo.VW_RPT_IMPRESORAS_USUARIOS
AS
	SELECT 
		UP.ID_ADM
	,	UP.ID_USUARIO	
	,	A.ID_AGENTE
	,	A.COD_AGENTE
	,	A.DESCRIPCION_AGENTE		
	,	I.ID_IMPRESORA
	,	I.NOMBRE_IMPRESORA
	,	I.DESCRIPCION_IMPRESORA	
	,	I.PROPIEDADES
	,	I.PARAMETROS
	,	UP.IMPRESORA_DEFAULT
	,	P.ID_PROPOSITO
	,	P.DESCRIPCION_PROPOSITO
	,	T.ID_TP_IMPRESORA
	,	T.DESC_TP_IMPRESORA
	,	E.ID_ESTADO
	,	E.DESCRIPCION_ESTADO
	,	D.ID_TIPO_DOC
	,	D.DESC_TIPO_DOC
	FROM
				SIR_AGENTE				AS A WITH(NOLOCK)
	INNER JOIN	SIR_IMPRESORA			AS I WITH(NOLOCK)
			ON	A.ID_AGENTE = I.ID_AGENTE 
	INNER JOIN	SIR_PROPOSITO			AS P WITH(NOLOCK)
			ON	I.ID_PROPOSITO = P.ID_PROPOSITO 
	INNER JOIN	SIR_TIPO_IMPRESORA		AS T WITH(NOLOCK)
			ON	I.ID_TP_IMPRESORA = T.ID_TP_IMPRESORA 
	INNER JOIN	SIR_ESTADO_IMPRESORAS	AS E WITH(NOLOCK)
			ON	E.ID_ESTADO = I.ID_ESTADO 
	INNER JOIN SIR_TIPO_DOCUMENTO		AS D WITH(NOLOCK)
			ON  I.ID_TIPO_DOC	= D.ID_TIPO_DOC
	INNER JOIN SIR_USUARIO_IMPRESORAS  AS UP WITH(NOLOCK)
			ON UP.ID_IMPRESORA = I.ID_IMPRESORA
	--INNER JOIN USU_USUARIOS  AS U WITH(NOLOCK)
	--		ON UP.ID_ADM = U.ID_ADM
	--		AND UP.ID_USUARIO = U.ID_USUARIO	
			
GO



IF EXISTS(SELECT 1 FROM sys.views WHERE name='VW_RPT_AGENTES_IMPRESION')
BEGIN
	DROP VIEW dbo.VW_RPT_AGENTES_IMPRESION
END
GO

CREATE VIEW dbo.VW_RPT_AGENTES_IMPRESION
AS
	SELECT 
		A.ID_AGENTE
	,	A.COD_AGENTE
	,	A.DESCRIPCION_AGENTE		
	,	I.ID_IMPRESORA
	,	I.NOMBRE_IMPRESORA
	,	I.DESCRIPCION_IMPRESORA	
	,	I.PROPIEDADES
	,	I.PARAMETROS
	,	P.ID_PROPOSITO
	,	P.DESCRIPCION_PROPOSITO
	,	T.ID_TP_IMPRESORA
	,	T.DESC_TP_IMPRESORA
	,	E.ID_ESTADO
	,	E.DESCRIPCION_ESTADO
	,	D.ID_TIPO_DOC
	,	D.DESC_TIPO_DOC
	FROM
				SIR_AGENTE				AS A WITH(NOLOCK)
	INNER JOIN	SIR_IMPRESORA			AS I WITH(NOLOCK)
			ON	A.ID_AGENTE = I.ID_AGENTE 
	INNER JOIN	SIR_PROPOSITO			AS P WITH(NOLOCK)
			ON	I.ID_PROPOSITO = P.ID_PROPOSITO 
	INNER JOIN	SIR_TIPO_IMPRESORA		AS T WITH(NOLOCK)
			ON	I.ID_TP_IMPRESORA = T.ID_TP_IMPRESORA 
	INNER JOIN	SIR_ESTADO_IMPRESORAS	AS E WITH(NOLOCK)
			ON	E.ID_ESTADO = I.ID_ESTADO 
	INNER JOIN SIR_TIPO_DOCUMENTO		AS D WITH(NOLOCK)
			ON  I.ID_TIPO_DOC	= D.ID_TIPO_DOC
GO

use MMA_TEST001
go

IF EXISTS(SELECT 1 FROM sys.views WHERE name='VW_TRABAJOS_IMPRESION')
BEGIN
	DROP VIEW dbo.VW_TRABAJOS_IMPRESION	
END
GO

CREATE VIEW dbo.VW_TRABAJOS_IMPRESION
AS
	SELECT 
		UP.ID_ADM
	,	UP.ID_USUARIO
	,	A.ID_AGENTE
	,	A.COD_AGENTE
	,	A.DESCRIPCION_AGENTE
	,	I.ID_IMPRESORA
	,	I.NOMBRE_IMPRESORA
	,	I.DESCRIPCION_IMPRESORA
	,	I.PROPIEDADES
	,	I.PARAMETROS
	,	P.ID_PROPOSITO
	,	P.DESCRIPCION_PROPOSITO
	,	T.ID_TP_IMPRESORA
	,	T.DESC_TP_IMPRESORA
	,	E.ID_ESTADO
	,	E.DESCRIPCION_ESTADO
	,	J.ID_TRABAJO
	,	J.DOCUMENTO
	,	J.CONFIG_IMPRESION
	,	J.POS_COLA_IMPRESION
	,	X.ID_ESTADO_IMPRESION
	,	X.DESCRIPCION_EST_IMP
	,	D.ID_TIPO_DOC
	,	D.DESC_TIPO_DOC
	FROM 
				SIR_AGENTE				AS A WITH(NOLOCK)
	INNER JOIN	SIR_IMPRESORA			AS I WITH(NOLOCK)
			ON	A.ID_AGENTE = I.ID_AGENTE 
	INNER JOIN	SIR_PROPOSITO			AS P WITH(NOLOCK)
			ON	I.ID_PROPOSITO = P.ID_PROPOSITO 
	INNER JOIN	SIR_TIPO_IMPRESORA		AS T WITH(NOLOCK)
			ON	I.ID_TP_IMPRESORA = T.ID_TP_IMPRESORA 
	INNER JOIN	SIR_ESTADO_IMPRESORAS	AS E WITH(NOLOCK)
			ON	E.ID_ESTADO = I.ID_ESTADO 
	INNER JOIN	SIR_TRABAJOS_IMPRESION AS J WITH(NOLOCK)
			ON	J.ID_IMPRESORA = I.ID_IMPRESORA 			
	INNER JOIN	SIR_ESTADOS_IMPRESION	AS X WITH(NOLOCK)
			ON	J.ID_ESTADO_IMPRESION = X.ID_ESTADO_IMPRESION
	INNER JOIN SIR_TIPO_DOCUMENTO		AS D WITH(NOLOCK)
			ON  I.ID_TIPO_DOC	= D.ID_TIPO_DOC
	INNER JOIN SIR_USUARIO_IMPRESORAS  AS UP WITH(NOLOCK)
			ON UP.ID_IMPRESORA = I.ID_IMPRESORA
GO


IF EXISTS(SELECT 1 FROM sys.views WHERE name='VW_IMPRESORAS_DEFAULT_USUARIOS')
BEGIN
	DROP VIEW dbo.VW_IMPRESORAS_DEFAULT_USUARIOS
END
GO

CREATE VIEW dbo.VW_IMPRESORAS_DEFAULT_USUARIOS
AS
	SELECT 	
		U.ID_ADM	
	,	U.ID_USUARIO
	,	U.NOMBRE
	,	UI.IMPRESORA_DEFAULT
	,	ESTADO_USUARIO = U.ESTADO
	,	A.ID_AGENTE
	,	A.COD_AGENTE
	,	A.DESCRIPCION_AGENTE
	,	I.ID_IMPRESORA
	,	I.NOMBRE_IMPRESORA
	,	I.DESCRIPCION_IMPRESORA
	,	I.PROPIEDADES
	,	I.PARAMETROS
	,	P.ID_PROPOSITO
	,	P.DESCRIPCION_PROPOSITO
	,	T.ID_TP_IMPRESORA
	,	T.DESC_TP_IMPRESORA
	,	E.ID_ESTADO
	,	E.DESCRIPCION_ESTADO
	,	D.ID_TIPO_DOC
	,	D.DESC_TIPO_DOC
	FROM 
				SIR_AGENTE				AS A WITH(NOLOCK)
	INNER JOIN	SIR_IMPRESORA			AS I WITH(NOLOCK)
			ON	A.ID_AGENTE = I.ID_AGENTE 
	INNER JOIN	SIR_PROPOSITO			AS P WITH(NOLOCK)
			ON	I.ID_PROPOSITO = P.ID_PROPOSITO 
	INNER JOIN	SIR_TIPO_IMPRESORA		AS T WITH(NOLOCK)
			ON	I.ID_TP_IMPRESORA = T.ID_TP_IMPRESORA 
	INNER JOIN	SIR_ESTADO_IMPRESORAS	AS E WITH(NOLOCK)
			ON	E.ID_ESTADO = I.ID_ESTADO 
	INNER JOIN  SIR_USUARIO_IMPRESORAS	AS UI WITH(NOLOCK)
			ON  I.ID_IMPRESORA = UI.ID_IMPRESORA 
	INNER JOIN	USU_USUARIOS			AS U WITH(NOLOCK)
			ON	UI.ID_ADM = U.ID_ADM
			AND UI.ID_USUARIO = U.ID_USUARIO	
	INNER JOIN SIR_TIPO_DOCUMENTO		AS D WITH(NOLOCK)
			ON  I.ID_TIPO_DOC	= D.ID_TIPO_DOC
GO
